# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Develog
paginate:       5
baseurl:        ""
url:            "https://salmonholic.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Salmonholic M
  url:          http://salmonholic.github.io
  email:        mhjang@nextree.co.kr

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
